### ISSUE TITLE
NPM release for etherpad 1.7.0

### ISSUE THREAD

**Issue by Hiswe** [ether/ep_headings2#19]
Hi,

thanks for this plugin!
I've seen that you've updated the code for etherpad's 1.7.0 compatibility, but it's not yet published on NPM.
Is there anything preventing this? 
And if yes is there anything I can help with?

**Comment by ilmartyrk** [comment]
I don't have permissions to publish it to npm maybe @JohnMcLear  can help?

**Comment by Hiswe** [comment]
@ilmartyrk thank for the answer :)
Hope we can have a `1.0.0` soon! That's the only thing that prevents me to migrate to etherpad 1.7 :/

**Comment by Hiswe** [comment]
@ilmartyrk @JohnMcLear any news on that?

**Comment by ilmartyrk** [comment]
@Hiswe  Hi, no news, hope @JohnMcLear  will be kind and have some time to do it in near future :)

**Comment by Hiswe** [comment]
@ilmartyrk One thing that can be done is to update this repo's README with instructions like:

> ### Etherpad >= 1.7
>
> go in the etherpad's folder and type  `npm install ether/ep_headings2 --save`
>
> ### Etherpad < 1.7
>
> go in Etherpad's admin and install headings2 like any other plugin
>

**Comment by spctrlth** [comment]
Thanks @Hiswe ! The `npm install ether/ep_headings2 --save` didn't seem to work for some reason, but since only one file seems to have changed, I eventually got it working with

```shell
cd node_modules/ep_headings2
curl https://raw.githubusercontent.com/ether/ep_headings2/master/index.js -O
```
One problem now is that we're using a package manager to install the pads (on Yunohost) and we're a bit afraid to do it this way in production because we fear it may unexpectedly break things...

So **bump**
The fix has been done 17 months ago. Could someone push it to npm or give someone else access so they can push it plz? Especially since the Readme says it's already a fork because a previous owner stopped working on the project...

**Comment by JohnMcLear** [comment]
Published.  I don't really have the time to maintain npm packages on top of all the Github repos etc. so if anyone can help at all I'd be more than happy to add people to packages so they can publish when fixes land on repos :)

a huge amount of the plugins I authored just require some basic house keeping so would be suitable low hanging fruit for someone looking to contribute to Etherpad.

**Comment by Hiswe** [comment]
@JohnMcLear Thanks for your answer! And the work you've done so far.

I'm pretty sure @ilmartyrk can take care of this one ;)
He has done an amazing job maintaining it!
