### ISSUE TITLE
Numbered List with headings not possible

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/ep_headings2#28]
At the moment it isn't possible to create a numbered list with headings. Is this intended to provide? At the moment, the text jumps to the line below when formated as heading

![Etherpad_Orderer_List_Bug3](https://user-images.githubusercontent.com/44228345/82154983-ee012400-9871-11ea-8ac8-24a4959e5cb2.PNG)

**Comment by JohnMcLear** [comment]
@seballot display block related issue?

**Comment by Oremountainflorian** [comment]
When the text get's longer it also happens that it jumps to the line below

![grafik](https://user-images.githubusercontent.com/44228345/82155649-b9dc3200-9876-11ea-8824-261e3665914c.png)

**Comment by seballot** [comment]
Indeed first issue can be resolved with inline-block

re second issue, I cannot find a fix, but I think it's ok cause I'm not sure this will ever happen...

Actually, if @JohnMcLear you know how to change 

```html
<ol><li><h1>My Title</h1></li></ol>
```

to 

```html
<h1><ol><li>My Title</li></ol></h1>
```

it might solve the second issue, and also make the numbers looks like h1

![image](https://user-images.githubusercontent.com/17404254/82186928-e5e5ca80-98eb-11ea-9298-4a94c3d8c380.png)

instead of

![image](https://user-images.githubusercontent.com/17404254/82186953-f1d18c80-98eb-11ea-9a1b-e79084bc83e7.png)

**Comment by JohnMcLear** [comment]
Yea it's defo doable, means an additional hook that applies the plugin content before the internal etherpad content.  Currently it does this.

Etherpad Line Attributes > Plugin Line Attributes > Content

The new hook would need to do

Plugin Line Attributes > Etherpad Line Attributes > Content

It wouldn't be hard to do but would be time consuming and would need test coverage / documentation.  I don't see the reward Vs time spent on this at current when compared to the other more significant things we're working on :)

**Comment by seballot** [comment]
> I don't see the reward Vs time spent on this at current when compared to the other more significant things we're working on :)

Yes ok !
